### ISSUE TITLE
Event dot gravity

### ISSUE THREAD

**Issue by Xpjay** [JoshHalvorson/calendar-date-range-picker#11]
<img width="294" alt="Capture d’écran 2021-09-01 à 18 19 14" src="https://user-images.githubusercontent.com/80956808/131707342-1a0b2d13-3048-4e42-a3f1-ddbbc3e3ba0b.png">

Possible to put the dot at the bottom of the text ? Or on the right like it is now it's okay but it "should" be "inside" the circle, not at the edge of it

**Comment by JoshHalvorson** [comment]
Good idea, definitely something that would be good to have, thanks again!
