### ISSUE TITLE
Add Event

### ISSUE THREAD

**Issue by Xpjay** [JoshHalvorson/calendar-date-range-picker#2]
Hi,

Possible to add "event" as a "dot" by passing a Calendar or list of calendar ?

**Comment by JoshHalvorson** [comment]
Hey! Yeah that could definitely be done, ill push that up when I get the chance. Thanks!

**Comment by JoshHalvorson** [comment]
Just pushed it up! Let me know what you think! And as always if there's something you think would be a good feature feel free to add it and make a pull request!
